-- SCHEMA FOR NOTIFICATION OWNER AND PROJECT 
GO
CREATE SCHEMA Request  AUTHORIZATION  Hewan  

 GRANT CREATE TABLE TO Hewan
 GRANT CREATE VIEW TO Hewan
 GRANT CREATE ROLE TO Hewan
 GRANT CREATE FUNCTION TO Hewan
 GRANT CREATE PROCEDURE TO Hewan
 GRANT  UPDATE TO HEWAN
 GRANT DELETE TO Hewan
GO
