-- SCHEMA FOR NOTIFICATION OWNER AND PROJECT 
GO
CREATE SCHEMA Request  AUTHORIZATION  Hewan  

 GRANT CREATE TABLE TO Hewan
 GRANT CREATE VIEW TO Hewan
 GRANT CREATE ROLE TO Hewan
 GRANT CREATE FUNCTION TO Hewan
 GRANT CREATE PROCEDURE TO Hewan
 GRANT  UPDATE TO HEWAN
 GRANT DELETE TO Hewan
GO

--CREATE SCHEMA FOR STAFF OWNER
GO
 CREATE SCHEMA Staff AUTHORIZATION Feleke

 GRANT CREATE TABLE TO Feleke
 GRANT CREATE VIEW TO Feleke
 GRANT CREATE ROLE TO Feleke
 GRANT CREATE FUNCTION TO Feleke
 GRANT CREATE PROCEDURE TO Feleke
 GRANT  UPDATE TO Feleke
 GRANT DELETE TO Feleke
 GO

 
 --CREATE SCHEMA FOR OWNER OF LANDOWNERS
 GO
  CREATE SCHEMA LandOwner AUTHORIZATION Dawit

 GRANT CREATE TABLE TO Dawit
 GRANT CREATE VIEW TO Dawit
 GRANT CREATE ROLE TO Dawit
 GRANT CREATE FUNCTION TO Dawit
 GRANT CREATE PROCEDURE TO Dawit
 GRANT  UPDATE TO Dawit
 GRANT DELETE TO Dawit
GO
